#! /bin/sh

xrandr --auto

xrandr --auto --output eDP --primary --mode 1920x1080
xrandr --auto --output HDMI-A-0 --mode 3840x2160 --above eDP

pgrep -x sxhkd > /dev/null || sxhkd &
#picom &
/usr/libexec/polkit-gnome-authentication-agent-1 &
#/usr/bin/nm-applet &
sh $HOME/Documents/scroll_trackball.sh &
$HOME/.config/polybar/launch.sh &
hsetroot -solid '#2E3440' &
/usr/bin/kdeconnect-indicator &
#/usr/bin/gentoo-pipewire-launcher &
#feh --bg-fill $HOME/wallpaper/waves.png

bspc monitor eDP -d 1 2 3 4
bspc monitor HDMI-A-0 -d 5 6 7 8
bspc wm -O eDP HDMI-A-0

bspc config border_width         2
bspc config window_gap           1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#4C566A'
bspc config focused_border_color '#D8DEE9'

wmname LG3D

bspc rule -a URxvt state=floating
bspc rule -a "firefox" state=floating
bspc rule -a kitty state=floating
bspc rule -a Thunar state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a "Gnome-system-monitor" state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a "Gufw.py" state=floating
bspc rule -a Eom state=floating
bspc rule -a feh state=floating
bspc rule -a XTerm state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a '*:slack' desktop='^9' state=tiled follow=off
bspc rule -a '*:megasync' state=floating
bspc rule -a processing-app-Base state=floating
