#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
./.config/polybar/launch.sh &
feh --bg-fill $HOME/.config/walls/flowers.jpg

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#224f60'
bspc config focused_border_color '#6f89a9'

wmname LG3D

bspc rule -a URxvt state=floating
bspc rule -a KeePassXC state=floating
bspc rule -a Thunar state=floating
bspc rule -a Lxappearance state=floating
