#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#picom &
/usr/libexec/polkit-gnome-authentication-agent-1 &
#/usr/bin/nm-applet &
sh $HOME/Documents/scroll_trackball.sh &
$HOME/.config/polybar/launch.sh &
hsetroot -solid '#1c1c1c' &
/usr/bin/kdeconnect-indicator &
#feh --bg-fill $HOME/wallpaper/waves.png

# bspc config top_padding 27
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#2e313d'
bspc config focused_border_color '#5b5f71'

wmname LG3D

bspc rule -a URxvt state=floating
bspc rule -a kitty state=floating
bspc rule -a Thunar state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a "Gnome-system-monitor" state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a "Gufw.py" state=floating
bspc rule -a Eom state=floating
bspc rule -a feh state=floating
bspc rule -a XTerm state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a '*:slack' desktop='^9' state=tiled follow=off
bspc rule -a '*:megasync' state=floating
bspc rule -a processing-app-Base state=floating
