# Colors (Blood Moon)

# Default colors
[colors.primary]
background = '#10100E'
foreground = '#C6C6C4'

# Normal colors
[colors.normal]
black   = '#10100E'
red     = '#C40233'
green   = '#009F6B'
yellow  = '#FFD700'
blue    = '#0087BD'
magenta = '#9A4EAE'
cyan    = '#20B2AA'
white   = '#C6C6C4'

# Bright colors
[colors.bright]
black   = '#696969'
red     = '#FF2400'
green   = '#03C03C'
yellow  = '#FDFF00'
blue    = '#007FFF'
magenta = '#FF1493'
cyan    = '#00CCCC'
white   = '#FFFAFA'

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Semibold Italic"

[font.normal]
family = "Source Code Pro"
style = "Semibold"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
decorations = "full"
dynamic_title = true
